config/routes.rb
Classportal::Application.routes.draw do

  resources :user_courses

  resources :users

  resources :student_courses

  resources :courses

  resources :students

  resources :instructors

  resources :admins

  resources :conversations do
    resources :messages
  end

  root 'sessions#new'
  get '/login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get '/user_students'=> 'users#list_students', as: :list_students
  get '/user_instructors' => 'users#list_instructors', as: :list_instructors
  get '/admin_home_page' => 'users#admin_home_page', as: :admin_home_page

  get '/signup' => 'users#new', as: :signup
  get '/student_home_page' =>'users#student_home_page', as: :student_home_page

  get '/instructor_home_page' => 'users#instructor_home_page', as: :instructor_home_page
  get '/drop_course' => 'users#drop_course', as: :drop_course

  get '/student_enrollment_requests' => 'users#student_enrollment_requests', as: :student_enrollment_requests
  get '/enroll_student' => 'users#enroll_student', as: :enroll_student

  

end

app/views/admins/_form.html.erb
<%= form_for(@admin) do |f| %>
  <% if @admin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin.errors.count, "error") %> prohibited this admin from being saved:</h2>

      <ul>
      <% @admin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.email_field :email, :placeholder => 'Email' %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password, :placeholder=>'Password' %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admins/edit.html.erb
<h1>Editing admin</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin %> |
<%= link_to 'Back', admins_path %>

app/views/admins/home.html.erb
<% if admin_user %>
    <ul>
      <h2> USER PROFILE </h2>
      <li><%= admin_user.name %></li>
      <li><%= admin_user.email %></li>
      <li><%= link_to "Log out", logout_path, method: "delete" %></li>
      <li><%= link_to 'Edit your profile details', edit_admin_path(admin_user) %></li>
    </ul>

    <h1>Listing admins</h1>

    <table>
      <thead>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
      </thead>

      <tbody>
      <% @admins.each do |admin| %>
          <tr>
            <td><%= admin.name %></td>
            <td><%= admin.email %></td>
            <td><%= link_to 'Show', admin %></td>
            <% if admin_user != admin && admin.id!=1%>
            <td><%= link_to 'Destroy', admin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <% end %>
           </tr>
      <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'New Admin', new_admin_path %>
    <br><br>
    <%= link_to "Show all admins", admins_path %><br>
    <%= link_to "Show all students", students_path %><br>
    <%= link_to "Show all instructors", instructors_path %><br>
    <%= link_to "Show all courses", courses_path %><br>
    <%= link_to "Show all studentcourses", student_courses_path %><br>



<% else %>
    <ul>
      <li><%= link_to "Login", 'login' %></a></li>
    </ul>
<% end %>

app/views/admins/index.html.erb
<h1>Listing admins</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Password</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @admins.each do |admin| %>
      <tr>
        <td><%= admin.name %></td>
        <td><%= admin.email %></td>
        <td><%= admin.password %></td>
        <td><%= link_to 'Show', admin %></td>
        <td><%= link_to 'Edit', edit_admin_path(admin) %></td>
        <td><%= link_to 'Destroy', admin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Admin', new_admin_path %>
<%= link_to 'Back to Home Page', admin_home_page_path %>

app/views/admins/new.html.erb
<h1>New admin</h1>

<%= render 'form' %>

<%= link_to 'Back', admins_path %>

app/views/admins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @admin.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @admin.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @admin.password %>
</p>

<%= link_to 'Edit', edit_admin_path(@admin) %> |
<%= link_to 'Back to Home Page', admin_home_page_path %>