config/routes.rb
Classportal::Application.routes.draw do

  resources :user_courses

  resources :users

  resources :student_courses

  resources :courses

  resources :students

  resources :instructors

  resources :admins

  resources :conversations do
    resources :messages
  end

  root 'sessions#new'
  get '/login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get '/user_students'=> 'users#list_students', as: :list_students
  get '/user_instructors' => 'users#list_instructors', as: :list_instructors
  get '/admin_home_page' => 'users#admin_home_page', as: :admin_home_page

  get '/signup' => 'users#new', as: :signup
  get '/student_home_page' =>'users#student_home_page', as: :student_home_page

  get '/instructor_home_page' => 'users#instructor_home_page', as: :instructor_home_page
  get '/drop_course' => 'users#drop_course', as: :drop_course

  get '/student_enrollment_requests' => 'users#student_enrollment_requests', as: :student_enrollment_requests
  get '/enroll_student' => 'users#enroll_student', as: :enroll_student

  

end

app/controllers/user_courses_controller.rb
class UserCoursesController < ApplicationController
  before_action :set_user_course, only: [:show, :edit, :update, :destroy]

  # GET /user_courses
  # GET /user_courses.json
  def index
    @user_courses = UserCourse.all
  end

  # GET /user_courses/1
  # GET /user_courses/1.json
  def show
  end

  # GET /user_courses/new
  def new
    @user_course = UserCourse.new
  end

  # GET /user_courses/1/edit
  def edit
  end

  # POST /user_courses
  # POST /user_courses.json
  def create
    @user_course = UserCourse.new(user_course_params)
    respond_to do |format|
      if @user_course.save
        format.html { redirect_to @user_course, notice: 'User course was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user_course }
      else
        format.html { render action: 'new' }
        format.json { render json: @user_course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_courses/1
  # PATCH/PUT /user_courses/1.json
  def update
    respond_to do |format|
      if @user_course.update(user_course_params)
        format.html { redirect_to @user_course, notice: 'User course was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user_course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_courses/1
  # DELETE /user_courses/1.json
  def destroy
    @user_course.destroy
    if logged_in_user.is_admin
    respond_to do |format|
      format.html { redirect_to user_courses_url }
      format.json { head :no_content }
    end
    elsif logged_in_user.is_instructor
      respond_to do |format|
        format.html { redirect_to user_courses_url }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to student_home_page_url }
        format.json { head :no_content }
      end
    end
end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_course
      @user_course = UserCourse.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_course_params
      params.require(:user_course).permit(:is_teaching, :is_enrolled, :has_requested_enrollment, :grade, :user_id, :course_id)
    end
end

app/helpers/user_courses_helper.rb
module UserCoursesHelper
end

app/views/user_courses/_form.html.erb
<%= form_for(@user_course) do |f| %>
  <% if @user_course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_course.errors.count, "error") %> prohibited this user_course from being saved:</h2>

      <ul>
      <% @user_course.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">


    <%= f.label :is_teaching %><br>
    <%= f.check_box :is_teaching %>


  </div>

  <div class="field">


    <%= f.label :is_enrolled %><br>
    <%= f.check_box :is_enrolled %>


  </div>

  <div class="field">


    <%= f.label :has_requested_enrollment %><br>
    <%= f.check_box :has_requested_enrollment %>


  </div>

  <div class="field">


    <%= f.label :grade %><br>
    <%= f.text_field :grade %>

    <div class="field">
      <%= f.label :user %><br />
      <%= f.collection_select(:user_id, User.all, :id, :name, { :prompt => 'Select a user', :selected => @user_course.user_id }, { class: 'form-control' }) %>
    </div>

    <div class="field">
      <%= f.label :course %><br />
      <%= f.collection_select(:course_id, Course.all, :id, :course_number, { :prompt => 'Select a course', :selected => @user_course.course_id }, { class: 'form-control' }) %>
    </div>

  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_courses/edit.html.erb
<h1>Editing user_course</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_course %> |
<%= link_to 'Back', user_courses_path %>

app/views/user_courses/index.html.erb
<h1>Listing user_courses</h1>

<table>
  <thead>
    <tr>

      <th> User </th>

      <th> course </th>

      <th>Is teaching</th>

      <th>Is enrolled</th>

      <th>Has requested enrollment</th>

      <th>Grade</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_courses.each do |user_course| %>
      <tr>
        <td><%= user_course.user_id %></td>

        <td><%= user_course.course_id %></td>

        <td><%= user_course.is_teaching %></td>

        <td><%= user_course.is_enrolled %></td>

        <td><%= user_course.has_requested_enrollment %></td>

        <td><%= user_course.grade %></td>

        <td><%= link_to 'Show', user_course %></td>
        <td><%= link_to 'Edit', edit_user_course_path(user_course) %></td>
        <td><%= link_to 'Destroy', user_course, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<br>

<%= link_to 'New User course', new_user_course_path %>
<%= link_to 'Back to Admin Page', admin_home_page_path %>

app/views/user_courses/new.html.erb
<h1>New user_course</h1>

<%= render 'form' %>

<%= link_to 'Back', user_courses_path %>

app/views/user_courses/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <strong>Is teaching:</strong>
  <%= @user_course.is_teaching %>
</p>


<p>
  <strong>Is enrolled:</strong>
  <%= @user_course.is_enrolled %>
</p>


<p>
  <strong>Has requested enrollment:</strong>
  <%= @user_course.has_requested_enrollment %>
</p>


<p>
  <strong>Grade:</strong>
  <%= @user_course.grade %>
</p>


<%= link_to 'Edit', edit_user_course_path(@user_course) %> |
<% if session[:role]=='admin' %>
<%= link_to 'Back', user_courses_path %>
<% end %>

<% if session[:role]=='instructor' %>
    <%= link_to 'Back', instructor_home_page_path %>
<% end %>
<% if session[:role]=='student' %>
    <%= link_to 'Back', student_home_page_path %>
<% end %>