config/routes.rb
Classportal::Application.routes.draw do

  resources :user_courses

  resources :users

  resources :student_courses

  resources :courses

  resources :students

  resources :instructors

  resources :admins

  resources :conversations do
    resources :messages
  end

  root 'sessions#new'
  get '/login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get '/user_students'=> 'users#list_students', as: :list_students
  get '/user_instructors' => 'users#list_instructors', as: :list_instructors
  get '/admin_home_page' => 'users#admin_home_page', as: :admin_home_page

  get '/signup' => 'users#new', as: :signup
  get '/student_home_page' =>'users#student_home_page', as: :student_home_page

  get '/instructor_home_page' => 'users#instructor_home_page', as: :instructor_home_page
  get '/drop_course' => 'users#drop_course', as: :drop_course

  get '/student_enrollment_requests' => 'users#student_enrollment_requests', as: :student_enrollment_requests
  get '/enroll_student' => 'users#enroll_student', as: :enroll_student

  

end

app/views/conversations/index.html.erb
<div class="ui segment">
  <h3>Mailbox</h3>

  <div class="ui list">
    <div class="item">
      <% @conversations.each do |conversation| %>
          <% if conversation.sender_id == logged_in_user.id || conversation.receiver_id == logged_in_user.id %>
              <% if conversation.sender_id == logged_in_user.id %>
                  <% receiver = User.find(conversation.receiver_id) %>
              <% else %>
                  <% receiver = User.find(conversation.sender_id) %>
              <% end %>
              <%= link_to receiver.name, conversation_messages_path(conversation)%>
          <% end %>
      <% end %>
    </div>
  </div>
</div>


<div class="ui segment">
  <h3>All Users</h3>
  <div class="ui list">
    <% @users.each do |user| %>
        <% if user.id != logged_in_user.id %>
            <div class="item">
              <%= user.name %> <%= link_to 'Message me!', conversations_path(sender_id: logged_in_user.id, receiver_id: user.id), method: 'post'%>
            </div>
        <% end %>
    <% end %>
  </div>
</div>


<% if session[:role]=='admin' %>
    <%= link_to 'Back to admin home page', admin_home_page_path %>
<% end %>

<% if session[:role]=='student' %>
    <%= link_to 'Back to student home page', student_home_page_path %>
<% end %>

<% if session[:role]=='instructor' %>
    <%= link_to 'Back to instructor home page', instructor_home_page_path %>
<% end %>