config/routes.rb
Classportal::Application.routes.draw do

  resources :user_courses

  resources :users

  resources :student_courses

  resources :courses

  resources :students

  resources :instructors

  resources :admins

  resources :conversations do
    resources :messages
  end

  root 'sessions#new'
  get '/login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get '/user_students'=> 'users#list_students', as: :list_students
  get '/user_instructors' => 'users#list_instructors', as: :list_instructors
  get '/admin_home_page' => 'users#admin_home_page', as: :admin_home_page

  get '/signup' => 'users#new', as: :signup
  get '/student_home_page' =>'users#student_home_page', as: :student_home_page

  get '/instructor_home_page' => 'users#instructor_home_page', as: :instructor_home_page
  get '/drop_course' => 'users#drop_course', as: :drop_course

  get '/student_enrollment_requests' => 'users#student_enrollment_requests', as: :student_enrollment_requests
  get '/enroll_student' => 'users#enroll_student', as: :enroll_student

  

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :user_courses
  has_many :courses, through: :user_courses


  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }, :presence => true

  #validates :is_admin
  #validates :is_instructor
  def self.search(search)
    if search
      self.where('name LIKE ?', "%#{search}%" )
    else
      self.all
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  before_action :require_logged_in, only: [:admin_home_page, :list_instructors, :list_students, :student_home_page, :instructor_home_page, :show]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  def admin_home_page
    if logged_in_user.is_admin
      @admins=User.where(:is_admin=>true)
    else
      flash[:notice] = "not enough rights !"
      redirect_to '/login'
    end
  end

  def list_students
    @students=User.where(:is_admin=>false ,:is_instructor=>false)
  end

  def list_instructors
    @instructors=User.where(:is_admin=>false, :is_instructor=>true)
  end

  def list_user_course
    @user_courses=UserCourse.all
    @users=User.all
    @courses=Course.all
  end

  def student_home_page
    @courses=Course.all
    #@own_courses=UserCourse.where(:user_id => [:sess])
    #@own_courses=UserCourse.where(:user_id=>session[:user_id]) if session[:user_id]
    @user=User.find_by_id(session[:user_id]) if session[:user_id]
    @my_courses=@user.courses
    @my_enrolled_courses=@user.user_courses.where(:is_enrolled=>true)
    @my_requested_courses=@user.user_courses.where(:has_requested_enrollment=>true)
    @my_course_mappings=@user.user_courses

    @un_enrolled_courses=@courses-@my_courses

  end

  def enroll_student
      @course=params[:course]
      @user_course=UserCourse.new(:user_id=>session[:user_id],:course_id=>@course, :has_requested_enrollment=>true, :is_teaching=>false, :is_enrolled=> false )

      respond_to do |format|
        if @user_course.save
          format.html { redirect_to @user_course, notice: 'Enrollment request generated.' }
          format.json { render action: 'show', status: :created, location: @user_course }
        else
          format.html { render action: 'student_home_page' }
          format.json { render json: @user_course.errors, status: :unprocessable_entity }
        end
      end

  end

  def instructor_home_page
    @instructor=User.find_by_id(session[:user_id]) if session[:user_id]
    @courses_taught=@instructor.courses
    @my_course_mappings=@instructor.user_courses

  end


  def student_enrollment_requests
      @my_course=params[:course]
      @course=Course.find_by_id(@my_course)
      @instructor=User.find_by_id(session[:user_id]) if session[:user_id]
      @students_enrollment_requests=UserCourse.where(:course_id=>@course.id)

  end

  def enroll
  end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :is_admin, :is_instructor)
    end

    def req_params
      params.require(:course).permit(:course_id)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">


    <%= f.label :name %><br>
    <%= f.text_field :name %>


  </div>

  <div class="field">


    <%= f.label :email %><br>
    <%= f.email_field :email %>


  </div>

  <div class="field">


    <%= f.label :password %><br>
    <%= f.password_field :password %>


  </div>
  <% if logged_in_user %>

  <div class="field">


    <%= f.label :is_admin %><br>
    <%= f.check_box :is_admin %>


  </div>

  <div class="field">


    <%= f.label :is_instructor %><br>
    <%= f.check_box :is_instructor %>


  </div>

  <% end %>

    <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/admin_home.html.erb
<% if logged_in_user.is_admin %>
    <ul>
      <h2> USER PROFILE </h2>
      <li><%= logged_in_user.name %></li>
      <li><%= logged_in_user.email %></li>
      <li><%= link_to "Log out", logout_path, method: "delete" %></li>
      <li><%= link_to 'Edit your profile details', edit_user_path(logged_in_user) %></li>
      <li><%= link_to "Admin home page", admin_home_page_path %></li>

    </ul>


    <h1>Listing admins</h1>

    <table>
      <thead>
      <tr>

        <th>Name</th>

        <th>Email</th>

        <th>Is admin</th>

        <th>Is instructor</th>

        <th colspan="3"></th>
      </tr>
      </thead>

      <tbody>
      <% @admins.each do |admin| %>
          <tr>

            <td><%= admin.name %></td>

            <td><%= admin.email %></td>

            <td><%= admin.is_admin %></td>

            <td><%= admin.is_instructor %></td>

            <td><%= link_to 'Show', admin %></td>
            <td><!%= link_to 'Edit', edit_user_path(admin) %></td>
            <% if admin!=logged_in_user && admin.id!=1 %>
            <td><%= link_to 'Destroy', admin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <% end %>
                </tr>
      <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'New Instructor/Admin', new_user_path %>

    <br><br>
    <!%= link_to "Show all admins", user_admins_path %><br>
    <%= link_to "Manage students", list_students_path %><br>
    <%= link_to "Manage instructors", list_instructors_path %><br>
    <%= link_to "Manage courses", courses_path %><br>
    <%= link_to "View all users", users_path %><br>

    <%= link_to "Show all studentcourses", user_courses_path %><br>


<% else %>
    <ul>

      <li><%= link_to "Login", 'login' %></a></li>
    </ul>
<% end %>

app/views/users/admin_home_page.html.erb
<% if logged_in_user.is_admin %>
    <ul>
      <h2> USER PROFILE </h2>
      <li><%= logged_in_user.name %></li>
      <li><%= logged_in_user.email %></li>
      <li><%= link_to "Log out", logout_path, method: "delete" %></li>
      <li><%= link_to 'Edit your profile details', edit_user_path(logged_in_user) %></li>
      <li><%= link_to "Admin home page", admin_home_page_path %></li>

    </ul>


    <h1>Listing admins</h1>

    <table>
      <thead>
      <tr>

        <th>Name</th>

        <th>Email</th>

        <th>Is admin</th>

        <th>Is instructor</th>

        <th colspan="3"></th>
      </tr>
      </thead>

      <tbody>
      <% @admins.each do |admin| %>
          <tr>

            <td><%= admin.name %></td>

            <td><%= admin.email %></td>

            <td><%= admin.is_admin %></td>

            <td><%= admin.is_instructor %></td>

            <td><%= link_to 'Show', admin %></td>
            <td><!%= link_to 'Edit', edit_user_path(admin) %></td>
            <% if admin!=logged_in_user && admin.id!=1 %>
            <td><%= link_to 'Destroy', admin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <% end %>
                </tr>
      <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'New Instructor/Admin', new_user_path %>

    <br><br>
    <!%= link_to "Show all admins", user_admins_path %><br>
    <%= link_to "Manage students", list_students_path %><br>
    <%= link_to "Manage instructors", list_instructors_path %><br>
    <%= link_to "Manage courses", courses_path %><br>
    <%= link_to "View all users", users_path %><br>

    <%= link_to "Show user course history", user_courses_path %><br>


<% else %>
    <ul>

      <li><%= link_to "Login", 'login' %></a></li>
    </ul>
<% end %>

app/views/users/adminhome.html.erb
<% if logged_in_user.is_admin%>
    <ul>
      <h2> USER PROFILE </h2>
      <li><%= logged_in_user.name %></li>
      <li><%= logged_in_user.email %></li>
      <li><%= link_to "Log out", logout_path, method: "delete" %></li>
      <li><%= link_to 'Edit your profile details', edit_user_path(logged_in_user) %></li>
    </ul>

    <h1>Listing users</h1>

    <table>
      <thead>
      <tr>

        <th>Name</th>

        <th>Email</th>

        <th>Password</th>

        <th>Is admin</th>

        <th>Is instructor</th>

        <th colspan="3"></th>
      </tr>
      </thead>

      <tbody>
      <% @users.each do |user| %>
          <tr>

            <td><%= user.name %></td>

            <td><%= user.email %></td>

            <td><%= user.password %></td>

            <td><%= user.is_admin %></td>

            <td><%= user.is_instructor %></td>

            <td><%= link_to 'Show', user %></td>
            <td><%= link_to 'Edit', edit_user_path(user) %></td>
            <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
      <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'New User', new_user_path %>



<% else %>
    <ul>
      <li><%= link_to "Login", 'login' %></a></li>
    </ul>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |

<% if session[:role]=='admin' %>
    <%= link_to 'Back to admin home page', admin_home_page_path %>
<% end %>

<% if session[:role]=='student' %>
    <%= link_to 'Back to student home page', student_home_page_path %>
<% end %>

<% if session[:role]=='instructor' %>
    <%= link_to 'Back to instructor home page', instructor_home_page_path %>
<% end %>

app/views/users/index.html.erb
<% if logged_in_user.is_admin %>
    <ul>
      <h2> USER PROFILE </h2>
      <li><%= logged_in_user.name %></li>
      <li><%= logged_in_user.email %></li>
      <li><%= link_to "Log out", logout_path, method: "delete" %></li>
      <li><%= link_to "Back to home page", admin_home_page_path %></li>

      <li><%= link_to 'Edit your profile details', edit_user_path(logged_in_user) %></li>
    </ul>

    <h1>Listing users</h1>

<table>
  <thead>
    <tr>

      <th>Name</th>

      <th>Email</th>


      <th>Is admin</th>

      <th>Is instructor</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>

        <td><%= user.name %></td>

        <td><%= user.email %></td>


        <td><%= user.is_admin %></td>

        <td><%= user.is_instructor %></td>

        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <% if user!=logged_in_user && user.id!=1 %>
            <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>



<% else %>
    <ul>
      <li><%= link_to "Login", 'login' %></a></li>
    </ul>
<% end %>

app/views/users/instructor_home_page.html.erb
<% if logged_in_user %>
    <ul>
      <h2> INSTRUCTOR PROFILE </h2>
      <li><%= logged_in_user.name %></li>
      <li><%= logged_in_user.email %></li>
      <li><%= link_to "Log out", logout_path, method: "delete" %></li>
      <li><%= link_to 'Edit your profile details', edit_user_path(logged_in_user) %></li>
      <li><%= link_to "Instructor home page", instructor_home_page_path %></li>

    </ul>


    <h1> Your courses </h1>

    <table>
      <thead>
      <tr>

        <th>Course number</th>

        <th>Title</th>

        <th>Description</th>

        <th>Start date</th>

        <th>End date</th>

        <th>Is active</th>

        <th>Notifications</th>

        <th>Deadlines</th>

        <!--th>Instructors</th-->

        <!--th>Grade</th-->

        <th colspan="3"></th>
      </tr>
      </thead>

      <tbody>
      <% @courses_taught.each do |course| %>
          <tr>

            <td><%= course.course_number %></td>

            <td><%= course.title %></td>

            <td><%= course.description %></td>

            <td><%= course.start_date %></td>

            <td><%= course.end_date %></td>

            <td><%= course.is_active %></td>

            <td><%= course.notifications %></td>

            <td><%= course.deadlines %></td>


            <!--td>
              <!% mapping.course.users.each do |user| %>
                  <!% if user.is_instructor %>
                      <li><!%= user.name %></li>
                  <!% end %>
              <!% end %>
            </td-->
            <!--td><!%= mapping.grade %></td-->
            <td><%= link_to 'Show course', course_path(course) %></td>
            <td><%= link_to 'Edit course', edit_course_path(course) %></td>

            <td><%= link_to 'Manage course requests and student grades', :action => :student_enrollment_requests, :course => course %></td>


          </tr>
      <% end %>
      </tbody>
    </table>

    <br>



    <br><br>
    <!%= link_to "Show all admins", user_admins_path %><br>
    <%= link_to "Show all courses", courses_path %><br>



<% else %>
    <ul>
      <li><%= link_to "Login", 'login' %></a></li>
    </ul>
<% end %>

app/views/users/list_instructors.erb
<% if logged_in_user.is_admin%>


    <html><body>
<h1>Listing users</h1>

<table>
  <thead>
  <tr>

    <th>Name</th>

    <th>Email</th>


    <th>Is admin</th>

    <th>Is instructor</th>

    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @instructors.each do |user| %>
      <tr>

        <td><%= user.name %></td>

        <td><%= user.email %></td>

        <td><%= user.is_admin %></td>

        <td><%= user.is_instructor %></td>

        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>


<td><%= link_to 'Add Instructor', new_user_path %></td>

<td><%= link_to 'Back to Home Page', admin_home_page_path %></td>


<br>
</body></html>

<% else %>
    <ul>
      <li><%= link_to "Login", 'login' %></a></li>
    </ul>
<% end %>

app/views/users/list_students.html.erb
<html><body>
<h1>Listing users</h1>

<table>
  <thead>
  <tr>

    <th>Name</th>

    <th>Email</th>

    <th>Is admin</th>

    <th>Is instructor</th>

    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @students.each do |user| %>
      <tr>

        <td><%= user.name %></td>

        <td><%= user.email %></td>

        <td><%= user.is_admin %></td>

        <td><%= user.is_instructor %></td>

        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>


<td><%= link_to 'Back to Home Page', admin_home_page_path %></td>


<br>
</body></html>

app/views/users/list_user_course.html.erb
<h1>Listing Users courses table</h1>

<table>
  <thead>
  <tr>

    <th>Course number</th>

    <th>Title</th>

    <th>Description</th>

    <th>Start date</th>

    <th>End date</th>

    <th>Is active</th>

    <th>Notifications</th>

    <th>Deadlines</th>

    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @user_courses.each do |uc| %>
      <tr>

        <td><%= uc.user_id %></td>

        <td><%= uc.course_id %></td>

        <td><%= uc.is_enrolled %></td>

        <td><%= uc.is_teaching %></td>

        <td><%= uc.is_requesting %></td>

        <% if logged_in_user.is_admin %>
            <td><%= link_to 'Show', uc %></td>
            <td><%= link_to 'Edit', edit_u_path(course) %></td>
            <td><%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<% if logged_in_user.is_admin %>
    <%= link_to 'Add New Course', new_course_path %><br>
    <%= link_to 'Back to admin home page', admin_home_page_path %>
<% end %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back to home page', admin_home_page_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>


<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>


<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>


<p>
  <strong>Is admin:</strong>
  <%= @user.is_admin %>
</p>


<p>
  <strong>Is instructor:</strong>
  <%= @user.is_instructor %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %>

<% if session[:role]=='admin' %>
<%= link_to 'Back to admin home page', admin_home_page_path %>
<% end %>

<% if session[:role]=='student' %>
    <%= link_to 'Back to student home page', student_home_page_path %>
<% end %>

<% if session[:role]=='instructor' %>
    <%= link_to 'Back to instructor home page', instructor_home_page_path %>
<% end %>

app/views/users/student_enrollment_requests.html.erb
<h1>Listing user_courses</h1>

<table>
  <thead>
  <tr>

    <th> User </th>

    <th> course </th>

    <th>Is teaching</th>

    <th>Is enrolled</th>

    <th>Has requested enrollment</th>

    <th>Grade</th>

    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @students_enrollment_requests.each do |user_course| %>
      <tr>
        <td><%= user_course.user_id %></td>

        <td><%= user_course.course_id %></td>

        <td><%= user_course.is_teaching %></td>

        <td><%= user_course.is_enrolled %></td>

        <td><%= user_course.has_requested_enrollment %></td>

        <td><%= user_course.grade %></td>

        <td><%= link_to 'Show', user_course %></td>
        <td><%= link_to 'Edit', edit_user_course_path(user_course) %></td>
        <td><%= link_to 'Destroy', user_course, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Back to instructor home page', instructor_home_page_path %>

app/views/users/student_home_page.html.erb
<% if logged_in_user %>
    <ul>
      <h2> USER PROFILE </h2>
      <li><%= logged_in_user.name %></li>
      <li><%= logged_in_user.email %></li>
      <li><%= link_to "Log out", logout_path, method: "delete" %></li>
      <li><%= link_to 'Edit your profile details', edit_user_path(logged_in_user) %></li>
      <li><%= link_to "Student home page", student_home_page_path %></li>

    </ul>


    <h1> Your enrolled courses </h1>

    <table>
      <thead>
      <tr>

        <th>Course number</th>

        <th>Title</th>

        <th>Description</th>

        <th>Start date</th>

        <th>End date</th>

        <th>Is active</th>

        <th>Notifications</th>

        <th>Deadlines</th>

        <th>Instructors</th>

        <th>Grade</th>

        <th colspan="3"></th>
      </tr>
      </thead>

      <tbody>
      <% @my_enrolled_courses.each do |mapping| %>
          <tr>

            <td><%= mapping.course.course_number %></td>

            <td><%= mapping.course.title %></td>

            <td><%= mapping.course.description %></td>

            <td><%= mapping.course.start_date %></td>

            <td><%= mapping.course.end_date %></td>

            <td><%= mapping.course.is_active %></td>

            <td><%= mapping.course.notifications %></td>

            <td><%= mapping.course.deadlines %></td>


            <td>
              <% mapping.course.users.each do |user| %>
                  <% if user.is_instructor %>
                      <li><%= user.name %></li>
                  <% end %>
              <% end %>
            </td>
            <td><%= mapping.grade %></td>
            <td><%= link_to 'Show course', course_path(mapping.course) %></td>

            <td><%= link_to 'Drop course', mapping, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
      <% end %>
      </tbody>
    </table>



    <br>
    <h1> Your requested courses </h1>

    <table>
      <thead>
      <tr>

        <th>Course number</th>

        <th>Title</th>

        <th>Description</th>

        <th>Start date</th>

        <th>End date</th>

        <th>Is active</th>

        <th>Notifications</th>

        <th>Deadlines</th>

        <th>Instructors</th>

        <th>Grade</th>

        <th colspan="3"></th>
      </tr>
      </thead>

      <tbody>
      <% @my_requested_courses.each do |mapping| %>
          <tr>

            <td><%= mapping.course.course_number %></td>

            <td><%= mapping.course.title %></td>

            <td><%= mapping.course.description %></td>

            <td><%= mapping.course.start_date %></td>

            <td><%= mapping.course.end_date %></td>

            <td><%= mapping.course.is_active %></td>

            <td><%= mapping.course.notifications %></td>

            <td><%= mapping.course.deadlines %></td>


            <td>
              <% mapping.course.users.each do |user| %>
                  <% if user.is_instructor %>
                      <li><%= user.name %></li>
                  <% end %>
              <% end %>
            </td>
            <td><%= mapping.grade %></td>
            <td><%= link_to 'Show course', course_path(mapping.course) %></td>

          </tr>
      <% end %>
      </tbody>
    </table>


    <h1> Unenrolled courses </h1>

    <table>
      <thead>
      <tr>

        <th>Course number</th>

        <th>Title</th>

        <th>Description</th>

        <th>Start date</th>

        <th>End date</th>

        <th>Is active</th>

        <th>Notifications</th>

        <th>Deadlines</th>

        <th>Instructors</th>



        <th colspan="3"></th>
      </tr>
      </thead>

      <tbody>
      <% @un_enrolled_courses.each do |course| %>
          <tr>

            <td><%= course.course_number %></td>

            <td><%= course.title %></td>

            <td><%= course.description %></td>

            <td><%= course.start_date %></td>

            <td><%= course.end_date %></td>

            <td><%= course.is_active %></td>

            <td><%= course.notifications %></td>

            <td><%= course.deadlines %></td>


            <td>
              <% course.users.each do |user| %>
                  <% if user.is_instructor %>
                      <li><%= user.name %></li>
                  <% end %>
              <% end %>
            </td>
            <td><%= link_to 'Show course', course_path(course) %></td>
            <td><%= link_to 'Enroll', :action=>:enroll_student, :course=>course %></td>

          </tr>
      <% end %>
      </tbody>
    </table>

    <br><br>
    <!%= link_to "Show all admins", user_admins_path %><br>
    <%= link_to "Show all courses", courses_path %><br>



<% else %>
    <ul>
      <li><%= link_to "Login", 'login' %></a></li>
    </ul>
<% end %>